export interface Country {
  code: string;
  flag: string;
  label: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", flag: "🇦🇫", label: "Afghanistan" },
  { code: "AL", flag: "🇦🇱", label: "Albania" },
  { code: "DZ", flag: "🇩🇿", label: "Algeria" },
  { code: "AD", flag: "🇦🇩", label: "Andorra" },
  { code: "AO", flag: "🇦🇴", label: "Angola" },
  { code: "AR", flag: "🇦🇷", label: "Argentina" },
  { code: "AM", flag: "🇦🇲", label: "Armenia" },
  { code: "AU", flag: "🇦🇺", label: "Australia" },
  { code: "AT", flag: "🇦🇹", label: "Österreich" },
  { code: "AZ", flag: "🇦🇿", label: "Azerbaijan" },
  { code: "BH", flag: "🇧🇭", label: "البحرين" },
  { code: "BD", flag: "🇧🇩", label: "Bangladesh" },
  { code: "BY", flag: "🇧🇾", label: "Belarus" },
  { code: "BE", flag: "🇧🇪", label: "Belgique" },
  { code: "BZ", flag: "🇧🇿", label: "Belize" },
  { code: "BJ", flag: "🇧🇯", label: "Bénin" },
  { code: "BO", flag: "🇧🇴", label: "Bolivia" },
  { code: "BA", flag: "🇧🇦", label: "Bosna i Hercegovina" },
  { code: "BW", flag: "🇧🇼", label: "Botswana" },
  { code: "BR", flag: "🇧🇷", label: "Brasil" },
  { code: "BN", flag: "🇧🇳", label: "Brunei" },
  { code: "BG", flag: "🇧🇬", label: "България" },
  { code: "BF", flag: "🇧🇫", label: "Burkina Faso" },
  { code: "KH", flag: "🇰🇭", label: "Cambodia" },
  { code: "CM", flag: "🇨🇲", label: "Cameroun" },
  { code: "CA", flag: "🇨🇦", label: "Canada" },
  { code: "CV", flag: "🇨🇻", label: "Cabo Verde" },
  { code: "CF", flag: "🇨🇫", label: "Centrafrique" },
  { code: "TD", flag: "🇹🇩", label: "Tchad" },
  { code: "CL", flag: "🇨🇱", label: "Chile" },
  { code: "CN", flag: "🇨🇳", label: "中国" },
  { code: "CO", flag: "🇨🇴", label: "Colombia" },
  { code: "CG", flag: "🇨🇬", label: "Congo" },
  { code: "CD", flag: "🇨🇩", label: "Congo (RDC)" },
  { code: "CR", flag: "🇨🇷", label: "Costa Rica" },
  { code: "CI", flag: "🇨🇮", label: "Côte d'Ivoire" },
  { code: "HR", flag: "🇭🇷", label: "Hrvatska" },
  { code: "CU", flag: "🇨🇺", label: "Cuba" },
  { code: "CY", flag: "🇨🇾", label: "Cyprus" },
  { code: "CZ", flag: "🇨🇿", label: "Česko" },
  { code: "DK", flag: "🇩🇰", label: "Danmark" },
  { code: "DJ", flag: "🇩🇯", label: "Djibouti" },
  { code: "DO", flag: "🇩🇴", label: "República Dominicana" },
  { code: "EC", flag: "🇪🇨", label: "Ecuador" },
  { code: "EG", flag: "🇪🇬", label: "مصر" },
  { code: "SV", flag: "🇸🇻", label: "El Salvador" },
  { code: "GQ", flag: "🇬🇶", label: "Guinea Ecuatorial" },
  { code: "ER", flag: "🇪🇷", label: "Eritrea" },
  { code: "EE", flag: "🇪🇪", label: "Eesti" },
  { code: "SZ", flag: "🇸🇿", label: "Eswatini" },
  { code: "ET", flag: "🇪🇹", label: "Ethiopia" },
  { code: "FI", flag: "🇫🇮", label: "Suomi" },
  { code: "FR", flag: "🇫🇷", label: "France" },
  { code: "GA", flag: "🇬🇦", label: "Gabon" },
  { code: "GM", flag: "🇬🇲", label: "Gambia" },
  { code: "GE", flag: "🇬🇪", label: "საქართველო" },
  { code: "DE", flag: "🇩🇪", label: "Deutschland" },
  { code: "GH", flag: "🇬🇭", label: "Ghana" },
  { code: "GR", flag: "🇬🇷", label: "Ελλάδα" },
  { code: "GT", flag: "🇬🇹", label: "Guatemala" },
  { code: "GN", flag: "🇬🇳", label: "Guinée" },
  { code: "GY", flag: "🇬🇾", label: "Guyana" },
  { code: "HT", flag: "🇭🇹", label: "Haïti" },
  { code: "HN", flag: "🇭🇳", label: "Honduras" },
  { code: "HK", flag: "🇭🇰", label: "Hong Kong" },
  { code: "HU", flag: "🇭🇺", label: "Magyarország" },
  { code: "IS", flag: "🇮🇸", label: "Ísland" },
  { code: "IN", flag: "🇮🇳", label: "India" },
  { code: "ID", flag: "🇮🇩", label: "Indonesia" },
  { code: "IR", flag: "🇮🇷", label: "ایران" },
  { code: "IQ", flag: "🇮🇶", label: "العراق" },
  { code: "IE", flag: "🇮🇪", label: "Ireland" },
  { code: "IL", flag: "🇮🇱", label: "ישראל" },
  { code: "IT", flag: "🇮🇹", label: "Italia" },
  { code: "JM", flag: "🇯🇲", label: "Jamaica" },
  { code: "JP", flag: "🇯🇵", label: "日本" },
  { code: "JO", flag: "🇯🇴", label: "الأردن" },
  { code: "KZ", flag: "🇰🇿", label: "Қазақстан" },
  { code: "KE", flag: "🇰🇪", label: "Kenya" },
  { code: "KW", flag: "🇰🇼", label: "الكويت" },
  { code: "KG", flag: "🇰🇬", label: "Кыргызстан" },
  { code: "LA", flag: "🇱🇦", label: "ລາວ" },
  { code: "LV", flag: "🇱🇻", label: "Latvija" },
  { code: "LB", flag: "🇱🇧", label: "لبنان" },
  { code: "LR", flag: "🇱🇷", label: "Liberia" },
  { code: "LY", flag: "🇱🇾", label: "ليبيا" },
  { code: "LT", flag: "🇱🇹", label: "Lietuva" },
  { code: "LU", flag: "🇱🇺", label: "Luxembourg" },
  { code: "MO", flag: "🇲🇴", label: "Macau" },
  { code: "MG", flag: "🇲🇬", label: "Madagascar" },
  { code: "MW", flag: "🇲🇼", label: "Malawi" },
  { code: "MY", flag: "🇲🇾", label: "Malaysia" },
  { code: "MV", flag: "🇲🇻", label: "Maldives" },
  { code: "ML", flag: "🇲🇱", label: "Mali" },
  { code: "MT", flag: "🇲🇹", label: "Malta" },
  { code: "MR", flag: "🇲🇷", label: "Mauritanie" },
  { code: "MU", flag: "🇲🇺", label: "Mauritius" },
  { code: "MX", flag: "🇲🇽", label: "México" },
  { code: "MD", flag: "🇲🇩", label: "Moldova" },
  { code: "MN", flag: "🇲🇳", label: "Монгол" },
  { code: "ME", flag: "🇲🇪", label: "Crna Gora" },
  { code: "MA", flag: "🇲🇦", label: "المغرب" },
  { code: "MZ", flag: "🇲🇿", label: "Moçambique" },
  { code: "MM", flag: "🇲🇲", label: "Myanmar" },
  { code: "NA", flag: "🇳🇦", label: "Namibia" },
  { code: "NP", flag: "🇳🇵", label: "Nepal" },
  { code: "NL", flag: "🇳🇱", label: "Nederland" },
  { code: "NZ", flag: "🇳🇿", label: "New Zealand" },
  { code: "NI", flag: "🇳🇮", label: "Nicaragua" },
  { code: "NE", flag: "🇳🇪", label: "Niger" },
  { code: "NG", flag: "🇳🇬", label: "Nigeria" },
  { code: "KP", flag: "🇰🇵", label: "조선" },
  { code: "MK", flag: "🇲🇰", label: "Северна Македонија" },
  { code: "NO", flag: "🇳🇴", label: "Norge" },
  { code: "OM", flag: "🇴🇲", label: "عُمان" },
  { code: "PK", flag: "🇵🇰", label: "Pakistan" },
  { code: "PS", flag: "🇵🇸", label: "فلسطين" },
  { code: "PA", flag: "🇵🇦", label: "Panamá" },
  { code: "PG", flag: "🇵🇬", label: "Papua New Guinea" },
  { code: "PY", flag: "🇵🇾", label: "Paraguay" },
  { code: "PE", flag: "🇵🇪", label: "Perú" },
  { code: "PH", flag: "🇵🇭", label: "Philippines" },
  { code: "PL", flag: "🇵🇱", label: "Polska" },
  { code: "PT", flag: "🇵🇹", label: "Portugal" },
  { code: "PR", flag: "🇵🇷", label: "Puerto Rico" },
  { code: "QA", flag: "🇶🇦", label: "قطر" },
  { code: "RO", flag: "🇷🇴", label: "România" },
  { code: "RU", flag: "🇷🇺", label: "Россия" },
  { code: "RW", flag: "🇷🇼", label: "Rwanda" },
  { code: "SA", flag: "🇸🇦", label: "السعودية" },
  { code: "SN", flag: "🇸🇳", label: "Sénégal" },
  { code: "RS", flag: "🇷🇸", label: "Србија" },
  { code: "SG", flag: "🇸🇬", label: "Singapore" },
  { code: "SK", flag: "🇸🇰", label: "Slovensko" },
  { code: "SI", flag: "🇸🇮", label: "Slovenija" },
  { code: "SO", flag: "🇸🇴", label: "Soomaaliya" },
  { code: "ZA", flag: "🇿🇦", label: "South Africa" },
  { code: "KR", flag: "🇰🇷", label: "한국" },
  { code: "SS", flag: "🇸🇸", label: "South Sudan" },
  { code: "ES", flag: "🇪🇸", label: "España" },
  { code: "LK", flag: "🇱🇰", label: "Sri Lanka" },
  { code: "SD", flag: "🇸🇩", label: "السودان" },
  { code: "SR", flag: "🇸🇷", label: "Suriname" },
  { code: "SE", flag: "🇸🇪", label: "Sverige" },
  { code: "CH", flag: "🇨🇭", label: "Schweiz" },
  { code: "SY", flag: "🇸🇾", label: "سوريا" },
  { code: "TW", flag: "🇹🇼", label: "台灣" },
  { code: "TJ", flag: "🇹🇯", label: "Тоҷикистон" },
  { code: "TZ", flag: "🇹🇿", label: "Tanzania" },
  { code: "TH", flag: "🇹🇭", label: "ไทย" },
  { code: "TG", flag: "🇹🇬", label: "Togo" },
  { code: "TT", flag: "🇹🇹", label: "Trinidad & Tobago" },
  { code: "TN", flag: "🇹🇳", label: "تونس" },
  { code: "TR", flag: "🇹🇷", label: "Türkiye" },
  { code: "TM", flag: "🇹🇲", label: "Türkmenistan" },
  { code: "UG", flag: "🇺🇬", label: "Uganda" },
  { code: "UA", flag: "🇺🇦", label: "Україна" },
  { code: "AE", flag: "🇦🇪", label: "الإمارات" },
  { code: "GB", flag: "🇬🇧", label: "United Kingdom" },
  { code: "US", flag: "🇺🇸", label: "United States" },
  { code: "UY", flag: "🇺🇾", label: "Uruguay" },
  { code: "UZ", flag: "🇺🇿", label: "Oʻzbekiston" },
  { code: "VE", flag: "🇻🇪", label: "Venezuela" },
  { code: "VN", flag: "🇻🇳", label: "Việt Nam" },
  { code: "YE", flag: "🇾🇪", label: "اليمن" },
  { code: "ZM", flag: "🇿🇲", label: "Zambia" },
  { code: "ZW", flag: "🇿🇼", label: "Zimbabwe" },
];

export function getFlagByCode(code: string | null | undefined): string {
  if (!code) return "";
  const country = COUNTRIES.find((c) => c.code === code);
  return country?.flag ?? "";
}
