// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iukwvfyhforubyqgguwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1a3d2ZnloZm9ydWJ5cWdndXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5ODIwMzksImV4cCI6MjA5MjU1ODAzOX0.XWjJBXc3xyp-hDHh2y8hN39loZh7vj-IuRB5bLJjV5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});